Traceback (most recent call last):
  File "C:\Users\37359\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
img_1 = create_clahe_grid_v2(img)
cv2.imwrite('../images/tradition/100-1-clahe_grid_v2.png', img_1)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31merror[0m                                     Traceback (most recent call last)
Cell [1;32mIn[4], line 1[0m
[1;32m----> 1[0m img_1 [38;5;241m=[39m [43mcreate_clahe_grid_v2[49m[43m([49m[43mimg[49m[43m)[49m
[0;32m      2[0m cv2[38;5;241m.[39mimwrite([38;5;124m'[39m[38;5;124m../images/tradition/100-1-clahe_grid_v2.png[39m[38;5;124m'[39m, img_1)

Cell [1;32mIn[3], line 60[0m, in [0;36mcreate_clahe_grid_v2[1;34m(img)[0m
[0;32m     58[0m [38;5;28;01mfor[39;00m cl [38;5;129;01min[39;00m clip_limit:
[0;32m     59[0m     clahe [38;5;241m=[39m cv2[38;5;241m.[39mcreateCLAHE(clipLimit[38;5;241m=[39mcl, tileGridSize[38;5;241m=[39m([38;5;241m8[39m, [38;5;241m8[39m))
[1;32m---> 60[0m     res [38;5;241m=[39m [43mclahe[49m[38;5;241;43m.[39;49m[43mapply[49m[43m([49m[43mimg[49m[43m)[49m
[0;32m     61[0m     res_list[38;5;241m.[39mappend(res)
[0;32m     63[0m img [38;5;241m=[39m np[38;5;241m.[39mhstack(res_list)

[1;31merror[0m: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function '`anonymous-namespace'::CLAHE_Impl::apply'

error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\clahe.cpp:353: error: (-215:Assertion failed) _src.type() == CV_8UC1 || _src.type() == CV_16UC1 in function '`anonymous-namespace'::CLAHE_Impl::apply'


